### PR TITLE
fix dumped data structure

### PR DESCRIPTION
**Pull request by stmuk**

### CODE REVIEW

**Comment by tony-o** [comment]
why would i merge this?

**Comment by stmuk** [comment]
To fix the test failure with the current rakudobrew version

**Comment by tony-o** [comment]
Not sure how this is the right fix for `rakudobrew` failing to test something that should obviously work but .. merged.

**Comment by stmuk** [comment]
I think the behaviour of rakudo has recently changed leading to the dumped
data structure being slightly different -- it's not obviousily broken just
different.

On 30 July 2015 at 21:05, tony-o notifications@github.com wrote:

> Not sure how this is the right fix for rakudobrew failing to test
> something that should obviously work but .. merged.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tony-o/perl6-data-dump/pull/2#issuecomment-126463774.

## 

4096R/EA75174B Steve Mynott steve.mynott@gmail.com

**Comment by tony-o** [comment]
No worries - it's all vapor-ware until it isn't

**Pull request merged**
