### PR TITLE
Add dumping for Pair and IO::Path type objects

### PR DESCRIPTION
**Pull request by samcv**
Also fix a few misc. things:
* Added a test for dumping Pair's
* Strip some whitespace

* Add use lib 'lib' for tests so when they are run they use local, not installed module.
  Running prove without this causes an installed module to take precedence
  and the tests run using the installed version of the module, not the one in
  the folder.

### CODE REVIEW

**Review by tony-o — CHANGES_REQUESTED** [review]
I don't think the `use lib 'lib';` stuff should live here - you should be running tests with `prove -e 'perl6' -lrv t/` (the `-l` flag tells it to check local first: see [here](https://linux.die.net/man/1/prove)).  

If you're running the tests individually use `perl6 -Ilib t/xyz.t`

If you take this out then I'll merge it.

**Comment by samcv** [comment]
Okay I will remove those if you object. I have also made some changes so that Pairs and Hashes are printed out differently than each other. I also made it so that Hashes or Pairs with empty strings as keys don't print out ` => 'bar'` and now print out `"" => 'bar'`

**Comment by samcv** [comment]
Hash with empty key:
```
{
   "" => "bar".Str,
}
Here is how it prints out now, which now also creates Pair objects when evaluated as Perl 6 code
```
Pair with empty key:
`"" => "bar".Str`

I have also reverted the `use lib 'lib'`

**Review by tony-o — APPROVED** [review]

**Comment by tony-o** [comment]
Thank you for the PR @samcv

**Pull request merged**
